### ISSUE TITLE
Demo site?

### ISSUE THREAD

**Issue by DibbsZA** [tafax/angular-digest-auth#2]
Do you have a demo site where one can see your library in action? I can't seem to get it to work with my own code and I am wondering if I am misinterpreting your setup instructions somehow.

**Comment by nzamosenchuk** [comment]
Hi guys. I'll post question here. I'm really confused.

I have a JBoss server with it's standard Digest Authenticator that is slightly updated to use custom header. No other changes.

I've configured  angular-digest-auth. And trying to perform sigin previously setting the user name and password.

But what I see in network monitor, is that nonce sent by server and responded by library doesn't match. But they should, aren't they? So the server always responds with 401 without proceeding with authentication. (but it's standard jboss authenticator with only the custom header).
